"""
scheme_config.py
Central registry of all 14 schemes – names, categories, weights, and source URLs.
This is the single source of truth; all other modules import from here.
"""

SCHEMES = [
    {
        "id": 1,
        "name": "Quant Large Cap Fund",
        "full_name": "Quant Large Cap Fund-Reg(G)",
        "category": "Large Cap",
        "weight": 10,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/quant-large-cap-fund-regular-plan/MES082",
        "mc_code": "MES082",
        "amfi_code": "120823",
    },
    {
        "id": 2,
        "name": "SBI Large & Midcap Fund",
        "full_name": "SBI Large & Midcap Fund-Reg(G)",
        "category": "Large & Mid Cap",
        "weight": 6,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/sbi-large-midcap-fund-direct-plan/MSB501",
        "mc_code": "MSB501",
        "amfi_code": "119598",
    },
    {
        "id": 3,
        "name": "DSP Large & Mid Cap Fund",
        "full_name": "DSP Large & Mid Cap Fund-Reg(G)",
        "category": "Large & Mid Cap",
        "weight": 9,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/dsp-large-mid-cap-fund-direct-plan/MDS580",
        "mc_code": "MDS580",
        "amfi_code": "119274",
    },
    {
        "id": 4,
        "name": "Bandhan Large & Mid Cap Fund",
        "full_name": "Bandhan Large & Mid Cap Fund-Reg(G)",
        "category": "Large & Mid Cap",
        "weight": 7,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/bandhan-large-mid-cap-fund-regular-plan-growth/MAG091",
        "mc_code": "MAG091",
        "amfi_code": "120505",
    },
    {
        "id": 5,
        "name": "Kotak Midcap Fund",
        "full_name": "Kotak Midcap Fund-Reg(G)",
        "category": "Mid Cap",
        "weight": 6,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/kotak-midcap-fund-regular-plan/MKM099",
        "mc_code": "MKM099",
        "amfi_code": "120483",
    },
    {
        "id": 6,
        "name": "Invesco India Smallcap Fund",
        "full_name": "Invesco India Smallcap Fund-Reg(G)",
        "category": "Small Cap",
        "weight": 7,
        "mc_url": "https://share.google/nVN3hkXVxBqh31Xly",
        "mc_code": "MLI1035",
        "amfi_code": "147977",
    },
    {
        "id": 7,
        "name": "HDFC Small Cap Fund",
        "full_name": "HDFC Small Cap Fund-Reg(G)",
        "category": "Small Cap",
        "weight": 5,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/hdfc-small-cap-fund-direct-plan/MMS025",
        "mc_code": "MMS025",
        "amfi_code": "118989",
    },
    {
        "id": 8,
        "name": "HDFC Flexi Cap Fund",
        "full_name": "HDFC Flexi Cap Fund(G)",
        "category": "Flexi Cap",
        "weight": 9,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/hdfc-flexi-cap-fund-direct-plan-/MHD1144",
        "mc_code": "MHD1144",
        "amfi_code": "100033",
    },
    {
        "id": 9,
        "name": "Kotak Multicap Fund",
        "full_name": "Kotak Multicap Fund-Reg(G)",
        "category": "Multi Cap",
        "weight": 7,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/kotak-multicap-fund-regular-plan/MKM1397",
        "mc_code": "MKM1397",
        "amfi_code": "149310",
    },
    {
        "id": 10,
        "name": "Canara Rob Multi Cap Fund",
        "full_name": "Canara Rob Multi Cap Fund-Reg(G)",
        "category": "Multi Cap",
        "weight": 7,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/canara-robeco-multi-cap-fund-direct-plan-growth/MCAA002",
        "mc_code": "MCAA002",
        "amfi_code": "149340",
    },
    {
        "id": 11,
        "name": "SBI Infrastructure Fund",
        "full_name": "SBI Infrastructure Fund-Reg(G)",
        "category": "Multi Cap*",
        "weight": 6,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/sbi-infrastructure-fund-direct-plan/MSB520",
        "mc_code": "MSB520",
        "amfi_code": "119223",
    },
    {
        "id": 12,
        "name": "ICICI Pru Focused Equity Fund",
        "full_name": "ICICI Pru Focused Equity Fund(G)",
        "category": "Focused",
        "weight": 7,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/icici-prudential-focused-equity-fund-retail-plan/MPI643",
        "mc_code": "MPI643",
        "amfi_code": "120586",
    },
    {
        "id": 13,
        "name": "Invesco India Focused Fund",
        "full_name": "Invesco India Focused Fund-Reg(G)",
        "category": "Focused",
        "weight": 7,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/invesco-india-focused-fund-direct-plan-growth/MLI1122",
        "mc_code": "MLI1122",
        "amfi_code": "149391",
    },
    {
        "id": 14,
        "name": "ICICI Pru Dividend Yield Fund",
        "full_name": "ICICI Pru Dividend Yield Equity Fund(G)",
        "category": "Dividend Yield",
        "weight": 7,
        "mc_url": "https://www.moneycontrol.com/mutual-funds/nav/icici-prudential-dividend-yield-equity-fund-regular-plan/MPI2056",
        "mc_code": "MPI2056",
        "amfi_code": "120505",
    },
]

SCHEME_NAMES = [s["name"] for s in SCHEMES]
SCHEME_CODES = {s["mc_code"]: s for s in SCHEMES}
AMFI_CODES = [s["amfi_code"] for s in SCHEMES]

CATEGORY_COLORS = {
    "Large Cap": "#1E88E5",
    "Large & Mid Cap": "#43A047",
    "Mid Cap": "#FB8C00",
    "Small Cap": "#E53935",
    "Flexi Cap": "#8E24AA",
    "Multi Cap": "#00ACC1",
    "Multi Cap*": "#546E7A",
    "Focused": "#F4511E",
    "Dividend Yield": "#FFB300",
}
